from utils.util import run, get_logger, cmd_is_available
from core.project import Project
import glob
import os

class JavaTask:
    def __init__(self, project: Project):
        self.project = project
        self.android_jar = os.path.join(self.project.sdk_dir, "platforms", f"android-{self.project.target_sdk}", "android.jar")
    
    def prepare(self):
        pass
    
    def start(self):
        get_logger().info("-- Compiling java files")

        java_available = cmd_is_available(self.project.bin_javac)
        if not java_available:
            raise Exception("-- javac not detected in PATH or SDK build-tools. Please set it in PATH.")
    
        java_classes_dir = self.project.java_classes_dir
        os.makedirs(java_classes_dir, exist_ok=True)
        
        java_files = self.project.find_java_files()
        java_r_files = self.project.find_java_files(self.project.gen_dir)
        java_binding_files = self.project.find_java_files(self.project.view_binding_dir)
        if not java_r_files:
            raise Exception("-- no java files generated by AAPT2")
        
        java_files.extend(java_r_files)
        java_files.extend(java_binding_files)
        
        lib_jars = self.project.find_lib_jars()
        classpath = os.pathsep.join([
            self.android_jar,
            *lib_jars
        ])

        
        args = [
            self.project.bin_javac,
            "-source", str(self.project.java_version),
            "-target", str(self.project.java_version),
            "-classpath", classpath,
            "-nowarn",
            "-proc:none",
            "-d", self.project.java_classes_dir,
            *java_files
        ]
        
        run(args)

class KotlinTask:
    def __init__(self, project: Project):
        self.project = project
        self.android_jar = os.path.join(self.project.sdk_dir, "platforms", f"android-{self.project.target_sdk}", "android.jar")
    
    def prepare(self):
        pass
    
    def start(self):
        kotlin_files = self.project.find_kotlin_files()
        if not kotlin_files:
            return

        get_logger().info("-- Compiling kotlin files")

        kotlinc_available = cmd_is_available(self.project.bin_kotlinc)
        
        kotlin_classes_dir = self.project.kotlin_classes_dir
        os.makedirs(kotlin_classes_dir, exist_ok=True)
        
        lib_jars = self.project.find_lib_jars()
        classpath = os.pathsep.join([
            self.android_jar,
            self.project.java_classes_dir,
            *lib_jars
        ])

        if kotlinc_available:
            args = [
                self.project.bin_kotlinc,
                *kotlin_files,
                "-classpath", classpath,
                "-d", self.project.kotlin_classes_dir,
                "-jvm-target", str(self.project.java_version)
            ]
        else:
            # Fallback: check for system Kotlin compiler JARs (e.g., Gradle bundle)
            gradle_jars = glob.glob("/usr/share/gradle-*/lib/*.jar")
            compiler_jar = [j for j in gradle_jars if "kotlin-compiler-embeddable" in j or "kotlin-compiler" in j]
            if compiler_jar and cmd_is_available("java"):
                cp_jars = os.pathsep.join(gradle_jars)
                args = [
                    "java",
                    "-cp", cp_jars,
                    "org.jetbrains.kotlin.cli.jvm.K2JVMCompiler",
                    "-no-stdlib",
                    *kotlin_files,
                    "-classpath", classpath,
                    "-d", self.project.kotlin_classes_dir,
                    "-jvm-target", str(self.project.java_version)
                ]
            else:
                raise Exception("> kotlinc not detected in PATH. Please set it in PATH.")
        
        run(args)
